Repository BookMark-Oneline/Client, pull requests merged in 2023-02, with the labels that each got.

#55 FIX #44 : 나의 서재 view 수정
  MyLib/MyLibTab.swift
Labels: fix

#54 FEAT #46 : apple 로그인 view 구현
  BookMark.xcodeproj/project.pbxproj
  BookMark.xcodeproj/xcuserdata/josuyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  BookMark.xcworkspace/xcuserdata/josuyeon.xcuserdatad/UserInterfaceState.xcuserstate
  BookMark/Assets.xcassets/Img/submain.imageset/Contents.json
  BookMark/Assets.xcassets/Img/submain.imageset/submain.pdf
  BookMark/Base.lproj/Main.storyboard
  BookMark/MainTabBarController.swift
  Login/LoginView.swift
  Login/LoginViewController.swift
  Login/back.png
  Login/ribon.png
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pastel/LICENSE
  Pods/Pastel/Pastel/Classes/PastelGradient.swift
  Pods/Pastel/Pastel/Classes/PastelLabel.swift
  Pods/Pastel/Pastel/Classes/PastelPoint.swift
  Pods/Pastel/Pastel/Classes/PastelView.swift
  Pods/Pastel/README.md
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Pods.xcodeproj/xcuserdata/josuyeon.xcuserdatad/xcschemes/Pastel.xcscheme
  Pods/Pods.xcodeproj/xcuserdata/josuyeon.xcuserdatad/xcschemes/Toast-Swift.xcscheme
  Pods/Pods.xcodeproj/xcuserdata/josuyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  Pods/Target Support Files/Pastel/Pastel-Info.plist
  Pods/Target Support Files/Pastel/Pastel-dummy.m
  Pods/Target Support Files/Pastel/Pastel-prefix.pch
  Pods/Target Support Files/Pastel/Pastel-umbrella.h
  Pods/Target Support Files/Pastel/Pastel.modulemap
  Pods/Target Support Files/Pastel/Pastel.xcconfig
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark-acknowledgements.markdown
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark-acknowledgements.plist
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark-frameworks-Debug-input-files.xcfilelist
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark-frameworks-Debug-output-files.xcfilelist
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark-frameworks-Release-input-files.xcfilelist
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark-frameworks-Release-output-files.xcfilelist
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark-frameworks.sh
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark.debug.xcconfig
  Pods/Target Support Files/Pods-BookMark/Pods-BookMark.release.xcconfig
  Pods/Target Support Files/Toast-Swift/Toast-Swift-Info.plist
  Pods/Target Support Files/Toast-Swift/Toast-Swift-dummy.m
  Pods/Target Support Files/Toast-Swift/Toast-Swift-prefix.pch
  Pods/Target Support Files/Toast-Swift/Toast-Swift-umbrella.h
  Pods/Target Support Files/Toast-Swift/Toast-Swift.modulemap
  Pods/Target Support Files/Toast-Swift/Toast-Swift.xcconfig
  Pods/Toast-Swift/LICENSE
  Pods/Toast-Swift/README.md
  Pods/Toast-Swift/Toast/Toast.swift
Labels: enhancement

#56 FEAT #49 : custom Alert 구현
  BookMark/Assets.xcassets/Img/leftImg.imageset/leftImg.pdf
  BookMark/Assets.xcassets/icon/trash.imageset/Contents.json
  BookMark/Assets.xcassets/icon/trash.imageset/trash.pdf
  Utility/CustomAlertViewController.swift
  Utility/Utils.swift
Labels: enhancement

#57 FEAT #48 : 게시글 삭제 & 책 삭제 추가
  BookMark/Assets.xcassets/icon/list.imageset/Contents.json
  BookMark/Assets.xcassets/icon/list.imageset/list.pdf
  Community/CommunityPost/PostDetailViewController.swift
  MyLib/BookDetailViewController.swift
  MyLib/MyLibTab.swift
  Utility/CustomAlertViewController.swift
Labels: enhancement

#62 FEAT #50 : 목표 독서 시간 view
  MyPage/MyPageTab.swift
  MyPage/SetTimeGoalViewController.swift
Labels: enhancement

#65 FIX #47 : 바코드 인식 안되는 문제 해결
  Community/CommunityTab.swift
  Community/JoinCommunityRequest.swift
  Community/SearchCommunityViewController.swift
  MyLib/Barcode/AddBookBarcode.swift
  MyLib/Barcode/AddBookBarcodeViewController.swift
  MyLib/Barcode/BarcodeReaderView.swift
  MyLib/Barcode/ConfirmBookViewController.swift
  MyLib/MyLibTab.swift
Labels: bug

#74 FIX: MyPageTab table view Cell Height 수정
  MyPage/MyPageTab.swift
Labels: bug

#102 FIX #100: API 1-1, 1-2
  MyLib/MyLibTab.swift
  Utility/DataClass.swift
  Utility/Network.swift
  Utility/Network_Sueyeon.swift
  Utility/UserClass.swift
Labels: bug, fix

#103 FEAT #79: API 2-11, 2-3 2-6, 2-12, 2-13, 2-4, 2-7-1, 2-7-2, 2-8 완료
  BookMark/Assets.xcassets/icon/heart.imageset/heart.pdf
  BookMark/Assets.xcassets/icon/heart_fill.imageset/Contents.json
  BookMark/Assets.xcassets/icon/heart_fill.imageset/heart_fill.pdf
  BookMark/Assets.xcassets/icon/heart_unfill.imageset/Contents.json
  BookMark/Assets.xcassets/icon/heart_unfill.imageset/heart_unfill.pdf
  Community/BookCommunitySettings/CreateCommunityViewController.swift
  Community/BookCommunitySettings/SetCommunityViewController.swift
  Community/CommunityMember/CommunityMemberViewController.swift
  Community/CommunityMember/WaitMemberViewController.swift
  Community/CommunityPost/PostDetailViewController.swift
  Utility/DataClass_sueyeon.swift
  Utility/Network.swift
  Utility/Network_Sueyeon.swift
Labels: enhancement, fix

#106 FIX: MyLibTab API 호출 시점 수정
  MyLib/Barcode/ConfirmBookViewController.swift
  MyLib/BookDetail/BookDetailView.swift
  MyLib/MyLibTab.swift
  Utility/DataClass.swift
  Utility/Network.swift
Labels: bug

#104 FEAT #81: API 2-1, 2-2, 2-9, 2-10, 2-14-1, 2-14-2, 2-15, 1-5
  Community/CommunityInsideViewController.swift
  Community/CommunityPost/CreatePostViewController.swift
  Community/CommunityTab.swift
  Community/JoinCommunityRequest.swift
  Community/SearchCommunityViewController.swift
  MyLib/Timer/ReadingTime.swift
  Utility/DataClassTintin.swift
  Utility/NetworkTintin.swift
Labels: enhancement, fix

#121 FIX #116: Community related Issue fixed
  Community/CommunityInsideViewController.swift
  Community/CommunityTab.swift
Labels: fix

#123 FEAT #105: 게시물 공지 등록 UI 구현
  Community/CommunityPost/PostDetailViewController.swift
  MyLib/Barcode/ConfirmBookViewController.swift
  Utility/Network.swift
Labels: enhancement
